services:
  db:
    image: postgres:16
    container_name: mass_postgres
    environment:
      POSTGRES_DB: mass_db
      POSTGRES_USER: mass_user
      POSTGRES_PASSWORD: mass_pass
    ports:
      - "5432:5432"
    volumes:
      - mass_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mass_user -d mass_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mass_pgdata:
